pipeline {
  agent {
    node {
      label 'master'
      }
    }

  stage('stage 1') {
    steps {
      sh 'echo this is stage one'
      }
    }

  stage('stage 2') {
    steps {
      script {
        openshift.withCluster() {
          openshift.withProject() {
            echo "stage 2: using project ${openshift.withProject()} in ${openshift.withCluster()}"
            }
          }
        }
      }
    }

  stage('manual approval') {
    steps {
      script {
        timeout(time: 60, unit: 'MINUTES') {
          input message: "proceed with next stage?" }
          }
        }
      }
}
