pipeline {
  agent {
    node {
      label 'master'
      }
    }
 stages {
  stage('stage 1') {
    steps {
      sh 'echo this is stage one'
      }
    }


  stage('manual approval') {
    steps {
      script {
        timeout(time: 60, unit: 'MINUTES') {
          input message: "proceed with next stage?" }
          }
        }
      }
 }
}
